### ISSUE TITLE
An unhandled exception has occurred:  A second operation was started on this context instance before a previous operation completed.

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#12]
click on Search

<img width="320" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/3f1feaa7-975f-4cb1-a0f3-3a186a0ca04a">

<img width="499" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/43d2b14f-19c9-45dd-a9fe-7399e0081727">

click on Home

<img width="270" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/758f439b-d40d-43d9-a6ea-f0036f00db6e">

click on Search

<img width="418" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/02c31465-9517-40f8-89d4-c38ea698286a">

:1  [2023-05-31T18:32:19.525Z] Error: System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at activities.Repository.UserProfil.UserProfileReposiotry.GetProfilesCountries() in C:\source\repos2\Zen33-Activities-SLN\activities\Repository\UserProfil\UserProfileReposiotry.cs:line 84
   at activities.Pages.Search.OnInitializedAsync() in C:\source\repos2\Zen33-Activities-SLN\activities\Pages\Search.razor:line 276
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
log @ blazor.server.js:1

<img width="877" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/7168fe4e-4de0-4dc1-b62c-d393aedfcf61">

**Comment by zen37** [comment]
occurred for admin to 
1. Manage Users
2. Search

<img width="896" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/288d63ce-373d-4f41-9a56-e67f5d3ac6bd">

**Comment by zen37** [comment]
same for Search (user not logged in)

<img width="905" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/186f9252-c4ac-42c7-9b32-09d8b5be887c">

**Comment by zen37** [comment]
**was able to consistently reproduce it**

according to the logs, countries are loaded first, then activities, then languages.

if user selects country and searches before languages are loaded, then

`fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'activities.Data.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()`

**Comment by thedoctor27** [comment]
i've changed the db context injection method,

you should never see that error again

fixed
